---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/manipulator/joint_states"
  gz_topic_name: "/world/manipulator_world/model/manipulator/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/manipulator/imu"
  gz_topic_name: "/world/manipulator_world/model/manipulator/link/link_drone/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS  
- ros_topic_name: "/EE/imu"
  gz_topic_name: "/world/manipulator_world/model/manipulator/link/link_3/sensor/imu_End_Effector/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS  
- ros_topic_name: "/dynamic_pose/info"
  gz_topic_name: "/world/manipulator_world/dynamic_pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/manipulator/pose_info"
  gz_topic_name: "/world/manipulator_world/pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS  
- ros_topic_name: "/link_drone/wrench"
  gz_topic_name: "/world/manipulator_world/wrench"
  ros_type_name: "ros_gz_interfaces/msg/EntityWrench"
  gz_type_name: "ignition.msgs.EntityWrench"
  direction: ROS_TO_GZ
- ros_topic_name: "/joint_1/command"
  gz_topic_name: "/joint_1/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/joint_2/command"
  gz_topic_name: "/joint_2/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/joint_3/command"
  gz_topic_name: "/joint_3/cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/force_torque_joint1"
  gz_topic_name: "/force_torque_joint1"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/force_torque_joint2"
  gz_topic_name: "/force_torque_joint2"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/force_torque_joint3"
  gz_topic_name: "/force_torque_joint3"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
